// Generated by designlang v7.0.0
// Source: https://string-tune.fiddle.digital/
package com.designlang.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object DesignTokens {
    val ActionPrimary = Color(0xFF101214)
    val ActionSecondary = Color(0xFFE6DFE4)
    val SurfaceDefault = Color(0xFF101214)
    val TextBody = Color(0xFFFFFFFF)
    val BrandPrimary = Color(0xFF101214)
    val BrandSecondary = Color(0xFFE6DFE4)
    val NeutralN100 = Color(0xFFFFFFFF)
    val NeutralN200 = Color(0xFF544D56)
    val NeutralN300 = Color(0xFFA399A8)
    val NeutralN400 = Color(0xFFA7A7B4)
    val NeutralN500 = Color(0xFF787878)
    val BackgroundBg0 = Color(0xFF101214)
    val BackgroundBg1 = Color(0xFFE6DFE4)
    val BackgroundBg2 = Color(0xFFFFFFFF)
    val BackgroundBg3 = Color(0xFFDAD3DC)
    val TextText0 = Color(0xFFFFFFFF)
    val TextText1 = Color(0xFF544D56)
    val TextText2 = Color(0xFFA399A8)
    val TextText3 = Color(0xFFE6DFE4)
    val TextText4 = Color(0xFF101214)
    val TextText5 = Color(0xFFC8C2CF)
    val TextText6 = Color(0xFFFF4F36)
    val TextText7 = Color(0xFF596375)
    val SpacingS0 = 0.dp
    val SpacingS1 = 7.dp
    val SpacingS2 = 20.dp
    val SpacingS3 = 27.dp
    val SpacingS4 = 32.dp
    val SpacingS5 = 36.dp
    val SpacingS6 = 42.dp
    val SpacingS7 = 45.dp
    val SpacingS8 = 52.dp
    val SpacingS9 = 61.dp
    val SpacingS10 = 85.dp
    val SpacingS11 = 99.dp
    val SpacingS12 = 112.dp
    val SpacingS13 = 120.dp
    val SpacingS14 = 150.dp
    val SpacingS15 = 154.dp
    val SpacingS16 = 195.dp
    val SpacingS17 = 225.dp
    val SpacingS18 = 256.dp
    val RadiusR0 = 8.dp
    val RadiusR1 = 11.dp
    val RadiusR2 = 15.dp
    val RadiusR3 = 20.dp
    val RadiusR4 = 27.dp
    val RadiusR5 = 30.dp
    val RadiusR6 = 36.dp
    val RadiusR7 = 40.dp
    val RadiusR8 = 50.dp
}
