// Generated by designlang v7.0.0
// Source: https://string-tune.fiddle.digital/
import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  // Semantic
  static const Color actionPrimary = Color(0xFF101214);
  static const Color actionSecondary = Color(0xFFE6DFE4);
  static const Color surfaceDefault = Color(0xFF101214);
  static const Color textBody = Color(0xFFFFFFFF);
  static const double spacingS0 = 0;
  static const double spacingS1 = 7;
  static const double spacingS2 = 20;
  static const double spacingS3 = 27;
  static const double spacingS4 = 32;
  static const double spacingS5 = 36;
  static const double spacingS6 = 42;
  static const double spacingS7 = 45;
  static const double spacingS8 = 52;
  static const double spacingS9 = 61;
  static const double spacingS10 = 85;
  static const double spacingS11 = 99;
  static const double spacingS12 = 112;
  static const double spacingS13 = 120;
  static const double spacingS14 = 150;
  static const double spacingS15 = 154;
  static const double spacingS16 = 195;
  static const double spacingS17 = 225;
  static const double spacingS18 = 256;
  static const double radiusR0 = 8;
  static const double radiusR1 = 11;
  static const double radiusR2 = 15;
  static const double radiusR3 = 20;
  static const double radiusR4 = 27;
  static const double radiusR5 = 30;
  static const double radiusR6 = 36;
  static const double radiusR7 = 40;
  static const double radiusR8 = 50;

  // Primitive palette
  static const Color brandPrimary = Color(0xFF101214);
  static const Color brandSecondary = Color(0xFFE6DFE4);
  static const Color neutralN100 = Color(0xFFFFFFFF);
  static const Color neutralN200 = Color(0xFF544D56);
  static const Color neutralN300 = Color(0xFFA399A8);
  static const Color neutralN400 = Color(0xFFA7A7B4);
  static const Color neutralN500 = Color(0xFF787878);
  static const Color backgroundBg0 = Color(0xFF101214);
  static const Color backgroundBg1 = Color(0xFFE6DFE4);
  static const Color backgroundBg2 = Color(0xFFFFFFFF);
  static const Color backgroundBg3 = Color(0xFFDAD3DC);
  static const Color textText0 = Color(0xFFFFFFFF);
  static const Color textText1 = Color(0xFF544D56);
  static const Color textText2 = Color(0xFFA399A8);
  static const Color textText3 = Color(0xFFE6DFE4);
  static const Color textText4 = Color(0xFF101214);
  static const Color textText5 = Color(0xFFC8C2CF);
  static const Color textText6 = Color(0xFFFF4F36);
  static const Color textText7 = Color(0xFF596375);
}

ThemeData buildDesignlangTheme() {
  return ThemeData(
    colorScheme: const ColorScheme.light(
      primary: DesignTokens.actionPrimary,
      surface: DesignTokens.surfaceDefault,
    ),
  );
}
