// Generated by designlang v7.0.0 — https://github.com/Manavarya09/design-extract
// Source: https://string-tune.fiddle.digital/
import SwiftUI

extension Color {
  init(hex: UInt32) {
    let r = Double((hex >> 16) & 0xFF) / 255
    let g = Double((hex >> 8) & 0xFF) / 255
    let b = Double(hex & 0xFF) / 255
    self.init(red: r, green: g, blue: b)
  }

  // MARK: Semantic
  static let actionPrimary = Color(hex: 0x101214)
  static let actionSecondary = Color(hex: 0xE6DFE4)
  static let surfaceDefault = Color(hex: 0x101214)
  static let textBody = Color(hex: 0xFFFFFF)
}

extension CGFloat {
  // MARK: Primitive spacing
  static let spacingS0: CGFloat = 0
  static let spacingS1: CGFloat = 7
  static let spacingS2: CGFloat = 20
  static let spacingS3: CGFloat = 27
  static let spacingS4: CGFloat = 32
  static let spacingS5: CGFloat = 36
  static let spacingS6: CGFloat = 42
  static let spacingS7: CGFloat = 45
  static let spacingS8: CGFloat = 52
  static let spacingS9: CGFloat = 61
  static let spacingS10: CGFloat = 85
  static let spacingS11: CGFloat = 99
  static let spacingS12: CGFloat = 112
  static let spacingS13: CGFloat = 120
  static let spacingS14: CGFloat = 150
  static let spacingS15: CGFloat = 154
  static let spacingS16: CGFloat = 195
  static let spacingS17: CGFloat = 225
  static let spacingS18: CGFloat = 256

  // MARK: Primitive radius
  static let radiusR0: CGFloat = 8
  static let radiusR1: CGFloat = 11
  static let radiusR2: CGFloat = 15
  static let radiusR3: CGFloat = 20
  static let radiusR4: CGFloat = 27
  static let radiusR5: CGFloat = 30
  static let radiusR6: CGFloat = 36
  static let radiusR7: CGFloat = 40
  static let radiusR8: CGFloat = 50
}

// MARK: Primitive palette (for direct use)
extension Color {
  static let brandPrimary = Color(hex: 0x101214)
  static let brandSecondary = Color(hex: 0xE6DFE4)
  static let neutralN100 = Color(hex: 0xFFFFFF)
  static let neutralN200 = Color(hex: 0x544D56)
  static let neutralN300 = Color(hex: 0xA399A8)
  static let neutralN400 = Color(hex: 0xA7A7B4)
  static let neutralN500 = Color(hex: 0x787878)
  static let backgroundBg0 = Color(hex: 0x101214)
  static let backgroundBg1 = Color(hex: 0xE6DFE4)
  static let backgroundBg2 = Color(hex: 0xFFFFFF)
  static let backgroundBg3 = Color(hex: 0xDAD3DC)
  static let textText0 = Color(hex: 0xFFFFFF)
  static let textText1 = Color(hex: 0x544D56)
  static let textText2 = Color(hex: 0xA399A8)
  static let textText3 = Color(hex: 0xE6DFE4)
  static let textText4 = Color(hex: 0x101214)
  static let textText5 = Color(hex: 0xC8C2CF)
  static let textText6 = Color(hex: 0xFF4F36)
  static let textText7 = Color(hex: 0x596375)
}

// typography.body: family=KHTeka size=225.28px weight=400 lineHeight=168.455px
